# Generated by Django 5.1.1 on 2024-10-04 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('dni', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('tfno', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=255)),
                ('fecha_registro', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('medicacion', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('dni', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clinica.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('dni', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clinica.usuario')),
                ('especialidad', models.CharField(max_length=100)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('raza', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('idH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.historialmedico')),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('motivo', models.CharField(max_length=255)),
                ('aceptada', models.BooleanField()),
                ('tipo', models.CharField(choices=[('U', 'Urgente'), ('R', 'Rutinaria')], max_length=1)),
                ('idM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.mascota')),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.veterinario')),
            ],
        ),
    ]
