# Generated by Django 5.1.1 on 2024-10-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='../static/images/defaultPFP.jpg', null=True, upload_to='usuarios_fotos/'),
        ),
    ]
