version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DATABASE_URL=mysql://root:bamboofun1@db:3306/clinicaveterinaria  
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    command: daphne -p 8001 -b 0.0.0.0 clinicaVeterinaria.asgi:application

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: clinicaveterinaria
      MYSQL_ROOT_PASSWORD: bamboofun1
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:latest

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  
    ports:
      - "8000:80"  
    depends_on:
      - web

volumes:
  db_data:
